apiVersion: v1
kind: Service
metadata:
  name: bookcatalog
spec:
  type: {{ .Values.service.type }}
  selector:
    app: bookcatalog
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
